spring.application.name=backend

# Verbindung zur lokalen MySQL-Datenbank "auspo"
spring.datasource.url=${DB_SERVER_URL:localhost}
spring.datasource.username=${DB_USERNAME:root}
# HIER DEIN LOKALES MYSQL-PASSWORT EINTRAGEN:
spring.datasource.password=${DB_PASSWORD:}


# JPA / Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

