spring.application.name=backend

# Verbindung zur lokalen MySQL-Datenbank "auspo"
spring.datasource.url=jdbc:mysql://localhost:3306/auspo?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
# HIER DEIN LOKALES MYSQL-PASSWORT EINTRAGEN:
spring.datasource.password=

# JPA / Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

